// examples/chain-template-spawn/components/staking/Overview.tsx
import { useState } from 'react';
import {
  Box,
  StakingAssetHeader,
  StakingClaimHeader,
} from '@interchain-ui/react';
import { useChain } from '@cosmos-kit/react';
import { ChainName } from 'cosmos-kit';
import { cosmos } from 'interchain-query';

import { getCoin } from '@/utils';
import { Prices, useTx } from '@/hooks';
import {
  sum,
  calcDollarValue,
  isGreaterThanZero,
  type ParsedRewards as Rewards,
} from '@/utils';

const { withdrawDelegatorReward } =
  cosmos.distribution.v1beta1.MessageComposer.fromPartial;

const Overview = ({
  balance,
  rewards,
  staked,
  updateData,
  chainName,
  prices,
}: {
  balance: string;
  rewards: Rewards;
  staked: string;
  updateData: () => void;
  chainName: ChainName;
  prices: Prices;
}) => {
  const [isClaiming, setIsClaiming] = useState(false);
  const { address } = useChain(chainName);
  const { tx } = useTx(chainName);

  const totalAmount = sum(balance, staked, rewards?.total ?? 0);
  const coin = getCoin(chainName);

  const onClaimRewardClick = async () => {
    setIsClaiming(true);

    if (!address) return;

    const msgs = rewards.byValidators.map(({ validatorAddress }) =>
      withdrawDelegatorReward({
        delegatorAddress: address,
        validatorAddress,
      })
    );

    await tx(msgs, {
      onSuccess: updateData,
    });

    setIsClaiming(false);
  };

  return (
    <>
      <Box mb={{ mobile: '$8', tablet: '$12' }}>
        <StakingAssetHeader
          imgSrc={
            coin.logo_URIs?.png ||
            coin.logo_URIs?.svg ||
            coin.logo_URIs?.jpeg ||
            ''
          }
          symbol={coin.symbol}
          totalAmount={Number(totalAmount) || 0}
          totalPrice={calcDollarValue(coin.base, totalAmount, prices)}
          available={Number(balance) || 0}
          availablePrice={calcDollarValue(coin.base, balance, prices)}
        />
      </Box>

      <Box mb={{ mobile: '$12', tablet: '$14' }}>
        <StakingClaimHeader
          symbol={coin.symbol}
          rewardsAmount={Number(rewards.total) || 0}
          stakedAmount={Number(staked) || 0}
          onClaim={onClaimRewardClick}
          isLoading={isClaiming}
          isDisabled={!isGreaterThanZero(rewards.total)}
        />
      </Box>
    </>
  );
};

export default Overview;

// examples/vue-example/src/components/stake-tokens/overview.vue
<script setup lang="ts">
import { Box} from '@interchain-ui/vue'
import { ref, defineProps, computed } from 'vue'
import { ParsedRewards } from '../../utils/stake-tokens/staking';
import { Prices } from '../../composables/usePrices';
import { useAssets } from '../../composables/useAssets';
import { sum, calcDollarValue, isGreaterThanZero } from '../../utils/stake-tokens/math';
const props = defineProps<{
  balance: string,
  rewards: ParsedRewards,
  staked: string,
  chainName: string,
  prices: Prices
}>()

const chainName = ref(props.chainName)
const { allAssets } = useAssets(chainName)

const totalAmount = computed(() => {
  return sum(props.balance, props.staked, props.rewards?.total ?? 0)
})

const onClaimRewardClick = async () => {
  // setIsClaiming(true);

  // if (!address) return;

  // const msgs = rewards.byValidators.map(({ validatorAddress }) =>
  //   withdrawDelegatorReward({
  //     delegatorAddress: address,
  //     validatorAddress,
  //   })
  // );

  // await tx(msgs, {
  //   onSuccess: updateData,
  // });

  // setIsClaiming(false);
};

</script>
<template>
<Box :mb="{ mobile: '$8', tablet: '$12' }">
  <div>
    StakingAssetHeader
    <img :src="allAssets[0]?.logo_URIs?.svg || allAssets[0]?.logo_URIs?.svg" width="30" />
    <div>symbol: {{ allAssets[0]?.symbol }}</div>
    <div>totalAmount: {{ totalAmount }}</div>
    <div>totalPrice: ${{ calcDollarValue(allAssets[0].base, totalAmount, prices) }}</div>
    <div>available: {{ balance || 0 }}</div>
    <div>availablePrice: ${{ calcDollarValue(allAssets[0].base, balance, prices) }}</div>
  </div>
</Box>
<Box :mb="{ mobile: '$12', tablet: '$14' }">
  <div>symbol: {{ allAssets[0]?.symbol }}</div>
  <div>rewardsAmount: {{ rewards.total }}</div>
  <div>stakedAmount: {{ staked }}</div>
  <button @click="onClaimRewardClick" :disabled="!isGreaterThanZero(rewards.total)">claim</button>
</Box>
</template>

<style scoped></style>
