// examples/telescope-authz/components/authz/GrantModal.tsx
import { useState } from 'react';
import { ChainName } from 'cosmos-kit';
import {
  BasicModal,
  Box,
  TextField,
  Button,
  Popover,
  PopoverTrigger,
  PopoverContent,
  SelectButton,
  ListItem,
  Stack,
  FieldLabel,
} from '@interchain-ui/react';
import { coin } from '@cosmjs/amino';
import { useChain } from '@cosmos-kit/react';
import { IoMdCalendar } from 'react-icons/io';
import Calendar from 'react-calendar';
import dayjs from 'dayjs';

import {
  getExponent,
  isPermissionCustomizable,
  PermissionId,
  PermissionItem,
  permissions,
} from '@/configs';
import { AuthorizationType } from '@/src/codegen/cosmos/staking/v1beta1/authz';
import { GrantMsg, useAuthzTx, useGrants } from '@/hooks';
import { getTokenByChainName, shiftDigits } from '@/utils';
import { CustomizationField } from './CustomizationField';

import styles from '@/styles/custom.module.css';

export type AccessList = {
  type: 'allowList' | 'denyList';
  addresses: string[];
};

type GrantModalProps = {
  isOpen: boolean;
  onClose: () => void;
  chainName: ChainName;
};

export const GrantModal = ({ isOpen, onClose, chainName }: GrantModalProps) => {
  const [isDropdownOpen, setIsDropdownOpen] = useState(false);
  const [isCalendarOpen, setIsCalendarOpen] = useState(false);

  const [granteeAddress, setGranteeAddress] = useState('');
  const [expiryDate, setExpiryDate] = useState<Date | null>(null);
  const [selectedPermission, setSelectedPermission] =
    useState<PermissionItem | null>(null);

  const [sendLimit, setSendLimit] = useState<number | undefined>(undefined);
  const [delegateLimit, setDelegateLimit] = useState<number | undefined>(
    undefined
  );
  const [accessList, setAccessList] = useState<AccessList>({
    type: 'allowList',
    addresses: [],
  });

  const [isGranting, setIsGranting] = useState(false);

  const { refetch } = useGrants(chainName);
  const { address } = useChain(chainName);
  const { authzTx, createGrantMsg } = useAuthzTx(chainName);

  const token = getTokenByChainName(chainName);
  const exponent = getExponent(chainName);
  const denom = token.base;

  const onModalClose = () => {
    setGranteeAddress('');
    setExpiryDate(null);
    setSelectedPermission(null);
    setSendLimit(undefined);
    setDelegateLimit(undefined);
    setIsGranting(false);
    setAccessList({ type: 'allowList', addresses: [] });
    onClose();
  };

  const onGrantClick = () => {
    if (!address || !granteeAddress || !expiryDate || !selectedPermission)
      return;

    setIsGranting(true);

    const sendMsg: GrantMsg = {
      grantType: 'send',
      customize: sendLimit
        ? {
            spendLimit: [coin(shiftDigits(sendLimit, exponent), denom)],
          }
        : undefined,
    };

    const delegateMsg: GrantMsg = {
      grantType: 'delegate',
      customize:
        delegateLimit || accessList.addresses.length > 0
          ? {
              authorizationType: AuthorizationType.AUTHORIZATION_TYPE_DELEGATE,
              maxTokens: coin(shiftDigits(delegateLimit, exponent), denom),
              [accessList.type]: { address: accessList.addresses },
            }
          : undefined,
    };

    const grantMsg: Record<PermissionId, GrantMsg> = {
      send: sendMsg,
      delegate: delegateMsg,
      vote: { grantType: 'vote' },
      'claim-rewards': { grantType: 'claim-rewards' },
    };

    const msg = createGrantMsg({
      grantee: granteeAddress,
      granter: address,
      expiration: expiryDate,
      ...grantMsg[selectedPermission.id],
    });

    authzTx({
      msgs: [msg],
      onSuccess: () => {
        refetch();
        onModalClose();
      },
      onComplete: () => {
        setIsGranting(false);
      },
    });
  };

  const isCustomizable =
    selectedPermission && isPermissionCustomizable(selectedPermission.id);

  return (
    <BasicModal
      title="Create Grant"
      isOpen={isOpen}
      onClose={onModalClose}
      closeOnClickaway={false}
    >
      <Box
        width={{ mobile: '100%', tablet: '$containerSm' }}
        display="flex"
        flexDirection="column"
        gap="$9"
        pt="$4"
      >
        <TextField
          id="grantee-address"
          value={granteeAddress}
          onChange={(e) => setGranteeAddress(e.target.value)}
          label="Grantee address"
          placeholder="Enter grantee address"
        />

        <Box>
          <FieldLabel htmlFor="" label="Permission" attributes={{ mb: '$4' }} />

          <Box display="flex" flexDirection="column" gap="$6">
            <Popover
              triggerType="click"
              isOpen={isDropdownOpen}
              setIsOpen={setIsDropdownOpen}
            >
              <PopoverTrigger>
                <SelectButton
                  className={styles.containerSm}
                  placeholder={selectedPermission?.name || 'Select permission'}
                  onClick={() => {}}
                />
              </PopoverTrigger>
              <PopoverContent showArrow={false}>
                <Stack direction="vertical">
                  {permissions.map((p) => (
                    <ListItem
                      key={p.id}
                      isActive={p.id === selectedPermission?.id}
                      className={styles.containerSm}
                      attributes={{
                        onClick: () => {
                          setSelectedPermission(p);
                          setIsDropdownOpen(false);
                        },
                      }}
                    >
                      {p.name}
                    </ListItem>
                  ))}
                </Stack>
              </PopoverContent>
            </Popover>

            {selectedPermission?.id === 'send' && (
              <CustomizationField
                permissionType={selectedPermission.id}
                value={sendLimit}
                onChange={(val) => {
                  if (!val) {
                    setSendLimit(undefined);
                    return;
                  }
                  setSendLimit(Number(val));
                }}
              />
            )}

            {selectedPermission?.id === 'delegate' && (
              <CustomizationField
                permissionType={selectedPermission.id}
                chainName={chainName}
                accessList={accessList}
                setAccessList={setAccessList}
                value={delegateLimit}
                onChange={(val) => {
                  if (!val) {
                    setDelegateLimit(undefined);
                    return;
                  }
                  setDelegateLimit(Number(val));
                }}
              />
            )}
          </Box>
        </Box>

        <Box position="relative">
          <TextField
            id="expiry-date"
            value={expiryDate ? dayjs(expiryDate).format('MM/DD/YYYY') : ''}
            label="Expiry Date"
            placeholder="Select expiry date"
          />
          <Box position="absolute" bottom="7px" right="10px">
            <Popover
              triggerType="click"
              offset={{ mainAxis: 12 }}
              isOpen={isCalendarOpen}
              setIsOpen={setIsCalendarOpen}
            >
              <PopoverTrigger>
                <IoMdCalendar size="26px" cursor="pointer" />
              </PopoverTrigger>
              <PopoverContent>
                <Calendar
                  locale="en-US"
                  value={expiryDate}
                  minDate={new Date()}
                  onChange={(val) => {
                    if (Array.isArray(val)) {
                      setExpiryDate(val[1]);
                      return;
                    }
                    setExpiryDate(val);
                  }}
                  onClickDay={() => {
                    setIsCalendarOpen(false);
                  }}
                />
              </PopoverContent>
            </Popover>
          </Box>
        </Box>

        <Box width="$full" mt="$9">
          <Button
            fluidWidth
            intent="tertiary"
            isLoading={isGranting}
            disabled={isGranting}
            onClick={onGrantClick}
          >
            Grant
          </Button>
        </Box>
      </Box>
    </BasicModal>
  );
};

// examples/vue-example/src/components/authz/grant-modal.vue
<script setup lang="ts">
import { Box, Modal, Button } from '@interchain-ui/vue'
import { ref, defineProps, computed, watch } from 'vue';
import { PermissionId, permissions } from '../../utils/authz/permissions';
import { useChain } from '@interchain-kit/vue';
import { useAuthzTx } from '../../composables/authz/useAuthzTx';
import { coin } from '@cosmjs/amino';
import { shiftDigits } from '../../utils/authz/calc';
import { useAssets } from '../../composables/useAssets';
import dayjs from 'dayjs';
import { SendAuthorization } from "../../codegen/cosmos/bank/v1beta1/authz";
import { GenericAuthorization } from 'osmojs/cosmos/authz/v1beta1/authz';
import { MsgGrant } from '../../codegen/cosmos/authz/v1beta1/tx';
import { useValidators } from '../../composables/authz/useValidators';
import { AuthorizationType, StakeAuthorization } from '../../codegen/cosmos/staking/v1beta1/authz';

type GrantModalProps = {
  isOpen: boolean;
  chainName: string;
};
const props = defineProps<GrantModalProps>()
const emits = defineEmits<{
  (event: 'close'): void;
}>()
const chainName = ref(props.chainName)
const { address } = useChain(chainName)
const granteeAddress = ref('')
const selectedPermissionId = ref<PermissionId>()
const sendLimit = ref<number>(2000)
const delegateLimit = ref<number>(2000)
const allowList = ref<{address: string[]}>({
  address: []
})
const denyList = ref<{address: string[]}>({
  address: []
})
const expiryDateStr = ref('')
const { authzTx } = useAuthzTx(chainName)

const expiryDate = computed(() => {
  return dayjs(expiryDateStr.value).toDate()
})

const onModalClose = () => {
  emits('close')
}
const { validators } = useValidators(chainName)

watch(validators, (vldtors) => {
  // let's say we put first two validator addresses to allowList
  // put next two addresses to denyList
  if (vldtors && vldtors.length > 4) {
    allowList.value.address = vldtors.slice(0, 2).map(vld => vld.address as string)
    denyList.value.address = vldtors.slice(2, 4).map(vld => vld.address as string)
  }
})

const { allAssets } = useAssets(chainName)

const exponent = computed(() => {
  return (allAssets[0].denom_units.find((unit) => unit.denom === allAssets[0].display))?.exponent
})

const denom = computed(() => {
  return allAssets[0].base
})

const onGrantClick = async() => {
  if (!address.value || !granteeAddress.value || !expiryDate.value || !selectedPermissionId.value)
    return;
    console.log('address', address)
    console.log('granteeAddress', granteeAddress.value)
    console.log('expiryDate', expiryDate.value)
    console.log('selectedPermission', selectedPermissionId.value)

  // const grantMsg: Record<PermissionId, GrantMsg> = {
  //   send: sendMsg,
  //   delegate: delegateMsg,
  //   vote: { grantType: 'vote' },
  //   'claim-rewards': { grantType: 'claim-rewards' },
  // };

  let msg = '' as any
  if (selectedPermissionId.value === 'send') {
    msg = {
      typeUrl: '/cosmos.authz.v1beta1.MsgGrant',
      value: {
        grant: {
          authorization: {
            typeUrl: '/cosmos.bank.v1beta1.SendAuthorization',
            value: SendAuthorization.encode({
              spendLimit: [coin(shiftDigits(sendLimit.value, exponent.value || 0), denom.value)],
            }).finish()
          },
          expiration: expiryDate.value // TOFIX: always been parsed to `1970-01-01T00:00:00.000Z`, don't know why.
          // expiration: new Date('2024-12-31T23:59:59Z')
          // expiration: {
          //   seconds: Long.fromNumber(Math.floor(new Date("2024-12-31T23:59:59Z").getTime() / 1000)),
          //   nanos: 0,
          // },
          // expiration: new Date('2024-12-31T23:59:59Z').getTime()
          // expiration: new Date("2024-12-31T23:59:59Z").toISOString()
        },
        grantee: granteeAddress.value,
        granter: address.value
      },
    }
  } else if (selectedPermissionId.value === 'vote') {
    msg = {
      typeUrl: '/cosmos.authz.v1beta1.MsgGrant',
      value: MsgGrant.fromPartial({
        grant: {
          authorization: {
            typeUrl: '/cosmos.authz.v1beta1.GenericAuthorization',
            value: GenericAuthorization.encode({
              msg: '/cosmos.gov.v1beta1.MsgVote'
            }).finish()
          },
          // expiration: new Date("2024-12-31"),
        },
        grantee: granteeAddress.value,
        granter: address.value
      })
    }
  } else if (selectedPermissionId.value === 'delegate') {
    msg = {
      typeUrl: "/cosmos.authz.v1beta1.MsgGrant",
      value: MsgGrant.fromPartial({
        grantee: granteeAddress.value,
        granter: address.value,
        grant: {
          authorization: {
            typeUrl: "/cosmos.staking.v1beta1.StakeAuthorization",
            value: StakeAuthorization.encode({
              authorizationType: AuthorizationType.AUTHORIZATION_TYPE_DELEGATE,
              maxTokens: coin(shiftDigits(delegateLimit.value, exponent.value || 0), denom.value),
              allowList: allowList.value,
              denyList: denyList.value
            }).finish(),
          },
          // expiration: new Date("2024-12-31"),
        },
      }),
    }
  }

  const res = await authzTx({
    msgs: [msg],
  })

  console.log('res>>', res)
}
</script>

<template>
<Modal
  header="header"
  :isOpen="isOpen"
  @close="onModalClose"
>
  <Box
    width="{ mobile: '100%', tablet: '$containerSm' }"
    display="flex"
    flexDirection="column"
    gap="$9"
    pt="$4"
  >
    <label for="granteeAddress">Grantee Address</label>
    <input id="granteeAddress" v-model="granteeAddress" type="text" placeholder="Enter grantee address" />
  </Box>
  <Box>
    <label for="permission">Permission</label>
    <select id="permission" v-model="selectedPermissionId" className="h-9 px-3 mr-4 border rounded-md shadow-sm" placeholder="Select permission">
      <option v-for="permission in permissions" :value="permission.id">{{ permission.name }}</option>
    </select>
    <input v-if="selectedPermissionId === 'send'" type="text" v-model="sendLimit" />
    <input v-else-if="selectedPermissionId === 'delegate'" type="text" v-model="delegateLimit">
    <label for="date">Select a date:</label>
    <input type="date" id="date" v-model="expiryDateStr" placeholder="Select expiry date"/>
  </Box>
  <Box width="$full" mt="$9">
    <Button
      fluidWidth
      intent="tertiary"
      @click="onGrantClick"
    >
      Grant
    </Button>
  </Box>
</Modal>
</template>

<style scoped></style>
