// examples/asset-list/pages/single-chain.tsx
import { defaultChainName as defaultChainName } from '@/config';
import { AssetList, Layout } from '@/components';
import { WalletSection } from '@/components/wallet';

export default function SingleChain() {
  return (
    <Layout>
      <WalletSection isMultiChain={false} />
      <AssetList selectedChainName={defaultChainName} />
    </Layout>
  );
}

// examples/asset-list-vue/src/views/single-chain.vue
<script setup lang="ts">
import Layout from '@/components/common/Layout.vue'
import WalletSection from '@/components/wallet/Wallet.vue'
import AssetListSection from '@/components/asset-list/AssetListSection.vue';

</script>

<template>
  <Layout>
    <WalletSection :isMultiChain="false" />
    <AssetListSection  />
  </Layout>
</template>

<style scoped></style>
