// examples/chain-template/components/staking/UndelegateModal.tsx
import { useState } from 'react';
import { cosmos } from 'interchain-query';
import { useChain } from '@cosmos-kit/react';
import { ChainName } from 'cosmos-kit';
import BigNumber from 'bignumber.js';
import {
  BasicModal,
  StakingDelegate,
  Callout,
  Box,
  Button,
} from '@interchain-ui/react';

import { Prices, UseDisclosureReturn, useTx } from '@/hooks';
import {
  calcDollarValue,
  formatValidatorMetaInfo,
  getAssetLogoUrl,
  getCoin,
  getExponent,
  isGreaterThanZero,
  shiftDigits,
  type ExtendedValidator as Validator,
} from '@/utils';

const { undelegate } = cosmos.staking.v1beta1.MessageComposer.fromPartial;

export const UndelegateModal = ({
  updateData,
  unbondingDays,
  chainName,
  logoUrl,
  selectedValidator,
  closeOuterModal,
  modalControl,
  prices,
}: {
  updateData: () => void;
  unbondingDays: string;
  chainName: ChainName;
  selectedValidator: Validator;
  closeOuterModal: () => void;
  modalControl: UseDisclosureReturn;
  logoUrl: string;
  prices: Prices;
}) => {
  const [amount, setAmount] = useState<number | undefined>(0);
  const [isUndelegating, setIsUndelegating] = useState(false);
  const [, forceUpdate] = useState(0);

  const { address } = useChain(chainName);
  const { tx } = useTx(chainName);

  const coin = getCoin(chainName);
  const exp = getExponent(chainName);

  const closeUndelegateModal = () => {
    setAmount(0);
    setIsUndelegating(false);
    modalControl.onClose();
  };

  const onUndelegateClick = async () => {
    if (!address || !amount) return;

    setIsUndelegating(true);

    const msg = undelegate({
      delegatorAddress: address,
      validatorAddress: selectedValidator.address,
      amount: {
        amount: shiftDigits(amount, exp),
        denom: coin.base,
      },
    });

    await tx([msg], {
      onSuccess: () => {
        updateData();
        closeOuterModal();
        closeUndelegateModal();
      },
    });

    setIsUndelegating(false);
  };

  const maxAmount = selectedValidator.delegation;

  return (
    <BasicModal
      title="Undelegate"
      isOpen={modalControl.isOpen}
      onClose={closeUndelegateModal}
    >
      <Box width={{ mobile: '100%', tablet: '$containerSm' }}>
        <StakingDelegate
          header={{
            title: selectedValidator.name,
            subtitle: formatValidatorMetaInfo(selectedValidator),
            avatarUrl: logoUrl,
          }}
          headerExtra={
            unbondingDays && (
              <Callout
                title="Once the unbonding period begins you will:"
                intent="error"
                iconName="errorWarningLine"
              >
                <Box as="ul" ml="$9">
                  <Box as="li">not receive staking rewards</Box>
                  <Box as="li">not be able to cancel the unbonding</Box>
                  <Box as="li">
                    need to wait {unbondingDays} days for the amount to be
                    liquid
                  </Box>
                </Box>
              </Callout>
            )
          }
          delegationItems={[
            {
              label: 'Your Delegation',
              tokenAmount: selectedValidator.delegation,
              tokenName: coin.symbol,
            },
          ]}
          inputProps={{
            inputToken: {
              tokenName: coin.symbol,
              tokenIconUrl: getAssetLogoUrl(coin),
            },
            notionalValue: amount
              ? calcDollarValue(coin.base, amount, prices)
              : undefined,
            value: amount,
            onValueInput: (val) => {
              if (!val) {
                setAmount(undefined);
                return;
              }

              if (new BigNumber(val).gt(maxAmount)) {
                setAmount(Number(maxAmount));
                forceUpdate((n) => n + 1);
                return;
              }

              setAmount(Number(val));
            },
            partials: [
              {
                label: '1/2',
                onClick: () => {
                  setAmount(new BigNumber(maxAmount).dividedBy(2).toNumber());
                },
              },
              {
                label: '1/3',
                onClick: () => {
                  setAmount(new BigNumber(maxAmount).dividedBy(3).toNumber());
                },
              },
              {
                label: 'Max',
                onClick: () => setAmount(Number(maxAmount)),
              },
            ],
          }}
          footer={
            <Button
              intent="tertiary"
              onClick={onUndelegateClick}
              disabled={!isGreaterThanZero(amount) || isUndelegating}
              isLoading={isUndelegating}
            >
              Undelegate
            </Button>
          }
        />
      </Box>
    </BasicModal>
  );
};

// examples/vue-example/src/components/stake-tokens/my-validators-modals/undelegate-modal.vue
<script setup lang="ts">
import { Callout, Box, Modal } from '@interchain-ui/vue'
import { ref, defineProps, computed } from 'vue'
import { ExtendedValidator, formatValidatorMetaInfo } from '../../../utils/stake-tokens/staking';
import { useParams } from '../../../composables/stake-tokens/useParams';
import { useAssets } from '../../../composables/common/useAssets';
import { calcDollarValue, isGreaterThanZero, shiftDigits } from '../../../utils/stake-tokens/math';
import { usePrices } from '../../../composables/common/usePrices';
import { useChain } from '@interchain-kit/vue';
import { cosmos, StdFee } from '../../../codegen';
import { useStargateClient } from '../../../composables/common/useStargateClient';
import { coins } from '@cosmjs/stargate';

const { undelegate } = cosmos.staking.v1beta1.MessageComposer.fromPartial;

const props = defineProps<{
  isOpen: boolean;
  selectedValidator: ExtendedValidator;
  logoUrl: string;
  chainName: string;
}>()
const emit = defineEmits<{
  (event: 'close'): void;
  (event: 'success'): void;
}>();
const chainName = ref(props.chainName)
const { address } = useChain(chainName)
const { allAssets } = useAssets(chainName)
const { prices } = usePrices(chainName)
const stargazeClient = useStargateClient(chainName)
const isSigning = ref(false)
const amount = ref(0)

const {data: unbondingDays} = useParams(chainName)

const closeModal = () => {
  emit('close')
}

const notionalValue = computed(() => {
  if (prices.value && amount.value) {
    return calcDollarValue(allAssets[0].base, amount.value, prices.value)
  }
  return ''
})

const exponent = computed(() => {
  return (allAssets[0].denom_units.find((unit) => unit.denom === allAssets[0].display))?.exponent
})

const handleUndelegate = async() => {
  if (!address.value || !amount.value || !exponent.value) return;
  const msg = undelegate({
    delegatorAddress: address.value,
    validatorAddress: props.selectedValidator.address,
    amount: {
      amount: shiftDigits(amount.value, exponent.value),
      denom: allAssets[0].base,
    },
  });
  console.log('msg>>', msg)
  
  const gasEstimate = await stargazeClient.value.simulate(
    address.value,
    [msg],
  );
  const gasLimit = Math.ceil(gasEstimate * 1.2);
  console.log('gasLimit>', gasLimit)

  const fee: StdFee = {
    amount: coins('1000', allAssets[0].base),
    gas: String(gasLimit)
  }

  isSigning.value = true
  try {
    const res = await stargazeClient.value.signAndBroadcast(
      address.value,
      [msg],
      fee
    )
    console.log('[signAndBroadcast result]', res)
    emit('success')
    closeModal()
  } catch(e) {
    console.error(e)
  } finally {
    isSigning.value = false
  }
}

</script>
<template>
<Modal
  header="header"
  :isOpen="isOpen"
  @close="closeModal"
>
  <Box :width="{ mobile: '100%', tablet: '$containerSm' }">
    <div>header: {{ selectedValidator.name }}</div>
    <div>subtitle: {{ formatValidatorMetaInfo(selectedValidator) }}</div>
    <div><img :src="logoUrl" width="40" /></div>
    <Callout
      title="Once the unbonding period begins you will:"
      intent="error"
      iconName="errorWarningLine"
    >
      <Box as="ul" ml="$9">
        <Box as="li">not receive staking rewards</Box>
        <Box as="li">not be able to cancel the unbonding</Box>
        <Box as="li">
          need to wait {{unbondingDays}} days for the amount to be
          liquid
        </Box>
      </Box>
    </Callout>
    <div>
      <div>Your Delegation</div>
      <div>tokenAmount: {{selectedValidator.delegation}}</div>
      <div>tokenName: {{ allAssets[0].symbol }}</div>
    </div>
    <div>
      <h2>input props:</h2>
      <div>
        <img :src="allAssets[0].logo_URIs?.png || allAssets[0].logo_URIs?.svg" width="40">
        <input type="text" v-model="amount" />
        <div>notionalValue: ${{ notionalValue }}</div>
      </div>
    </div>
    <div>
      <button 
        :disabled="!isGreaterThanZero(amount) || isSigning"
        @click="handleUndelegate"
      >
        Undelegate
      </button>
    </div>
  </Box>
</Modal>
</template>
<style scoped></style>
