// examples/vue-example/src/components/stake-tokens/my-validators-list.vue
<script setup lang="ts">
import { Button } from '@interchain-ui/vue'
import { ref, defineProps } from 'vue'
import { ExtendedValidator } from '../../utils/stake-tokens/staking';
import { useAssets } from '../../composables/common/useAssets';

const props = defineProps<{
  validators: ExtendedValidator[],
  logos: {
    [key: string]: string;
  },
  chainName: string
}>()

const chainName = ref(props.chainName)
const { allAssets } = useAssets(chainName)
</script>
<template>
<h2>My validators</h2>
<table cellpadding="5" cellspacing="0" border="1">
  <thead>
    <tr>
      <th>
        Validator
      </th>
      <th>
        Amount Staked
      </th>
      <th>
        Claimable Rewards
      </th>
      <th>
        Action
      </th>
    </tr>
  </thead>
  <tbody>
    <tr v-for="validator in validators" :key="validator.name">
      <td>
        {{ validator.name }}
        <img :src="logos?.[validator?.address]" width="40">
      </td>
      <td>
        {{ validator.delegation }}
        {{ allAssets[0].symbol }}
      </td>
      <td>
        {{ validator.reward }}
        {{ allAssets[0].symbol }}
      </td>
      <td>
        <Button>Manage</Button>
      </td>
    </tr>
  </tbody>
</table>
</template>

<style scoped></style>

// templates/chain-template/components/staking/MyValidatorsList.tsx
import React from 'react';
import { Dispatch, SetStateAction } from 'react';
import {
  Button,
  ValidatorList,
  ValidatorNameCell,
  ValidatorTokenAmountCell,
} from '@interchain-ui/react';
import { ChainName } from 'cosmos-kit';

import { getCoin, type ExtendedValidator as Validator } from '@/utils';

const MyValidatorsList = ({
  myValidators,
  openModal,
  chainName,
  logos,
  setSelectedValidator,
}: {
  myValidators: Validator[];
  chainName: ChainName;
  openModal: () => void;
  setSelectedValidator: Dispatch<SetStateAction<Validator | undefined>>;
  logos: {
    [key: string]: string;
  };
}) => {
  const coin = getCoin(chainName);

  return (
    <ValidatorList
      columns={[
        {
          id: 'validator',
          label: 'Validator',
          width: '196px',
          align: 'left',
          render: (validator: Validator) => (
            <ValidatorNameCell
              validatorName={validator.name}
              validatorImg={
                logos && validator.address in logos
                  ? logos[validator.address]
                  : ''
              }
            />
          ),
        },
        {
          id: 'amount-staked',
          label: 'Amount Staked',
          width: '196px',
          align: 'right',
          render: (validator: Validator) => (
            <ValidatorTokenAmountCell
              amount={validator.delegation}
              symbol={coin.symbol}
            />
          ),
        },
        {
          id: 'claimable-rewards',
          label: 'Claimable Rewards',
          width: '196px',
          align: 'right',
          render: (validator: Validator) => (
            <ValidatorTokenAmountCell
              amount={validator.reward}
              symbol={coin.symbol}
            />
          ),
        },
        {
          id: 'action',
          width: '196px',
          align: 'right',
          render: (validator) => (
            <Button
              variant="solid"
              intent="tertiary"
              size="sm"
              onClick={() => {
                openModal();
                setSelectedValidator(validator);
              }}
              attributes={{ ml: 'auto' }}
            >
              Manage
            </Button>
          ),
        },
      ]}
      data={myValidators}
      tableProps={{
        width: '$full',
      }}
    />
  );
};

export default React.memo(MyValidatorsList);
