// examples/vue-example/src/components/stake-tokens/my-validators-modals/validator-info-modal.vue
<script setup lang="ts">
import { Box, Modal } from '@interchain-ui/vue'
import { ref, defineProps } from 'vue'
import { ExtendedValidator, formatValidatorMetaInfo } from '../../../utils/stake-tokens/staking';
import { useAssets } from '../../../composables/common/useAssets';

const props = defineProps<{
  isOpen: boolean;
  selectedValidator: ExtendedValidator;
  logoUrl: string;
  chainName: string;
}>()
const chainName = ref(props.chainName)
const { allAssets } = useAssets(chainName)

const emit = defineEmits<{
  (event: 'close'): void;
  (event: 'undelegate'): void;
  (event: 'delegate'): void;
  (event: 'redelegate'): void;
}>();

const closeModal = () => {
  emit('close')
}

</script>
<template>
<Modal
  header="header"
  :isOpen="isOpen"
  @close="closeModal"
>
  <Box :width="{ mobile: '100%', tablet: '$containerSm' }">
    <div>header: {{ selectedValidator.name }}</div>
    <div>subtitle: {{ formatValidatorMetaInfo(selectedValidator) }}</div>
    <div><img :src="logoUrl" width="40" /></div>
    <div>description: {{ selectedValidator.description }}</div>
    <div>You Delegation: {{ selectedValidator.delegation }} {{ allAssets[0]?.symbol }}</div>
    <div style="display: flex;">
      <button @click="closeModal();emit('undelegate')">Undelegate</button>
      <button @click="closeModal();emit('redelegate')" style="margin-left: 100px;">Redelegate</button>
      <button @click="closeModal();emit('delegate')" style="margin-left: 100px;">Delegate</button>
    </div>
  </Box>
</Modal>
</template>

<style scoped></style>

// examples/chain-template-spawn/components/staking/ValidatorInfoModal.tsx
import { getCoin } from '@/utils';
import { ChainName } from 'cosmos-kit';
import {
  formatValidatorMetaInfo,
  type ExtendedValidator as Validator,
} from '@/utils';
import {
  BasicModal,
  Box,
  Button,
  StakingDelegate,
  Text,
} from '@interchain-ui/react';
import { UseDisclosureReturn } from '@/hooks';

export const ValidatorInfoModal = ({
  chainName,
  logoUrl,
  handleClick,
  modalControl,
  selectedValidator,
}: {
  chainName: ChainName;
  modalControl: UseDisclosureReturn;
  selectedValidator: Validator;
  handleClick: {
    openDelegateModal: () => void;
    openUndelegateModal: () => void;
    openSelectValidatorModal: () => void;
  };
  logoUrl: string;
}) => {
  const coin = getCoin(chainName);

  const { isOpen, onClose } = modalControl;
  const { openDelegateModal, openSelectValidatorModal, openUndelegateModal } =
    handleClick;

  return (
    <BasicModal title="Validator" isOpen={isOpen} onClose={onClose}>
      <Box width={{ mobile: '100%', tablet: '$containerSm' }}>
        <StakingDelegate
          header={{
            title: selectedValidator.name,
            subtitle: formatValidatorMetaInfo(selectedValidator),
            avatarUrl: logoUrl,
          }}
          headerExtra={
            selectedValidator.description && (
              <Text fontSize="$md">{selectedValidator.description}</Text>
            )
          }
          delegationItems={[
            {
              label: 'Your Delegation',
              tokenAmount: selectedValidator.delegation,
              tokenName: coin.symbol,
            },
          ]}
          footer={
            <Box display="flex" justifyContent="flex-end" gap="$8">
              <Button
                intent="secondary"
                onClick={() => {
                  onClose();
                  openUndelegateModal();
                }}
              >
                Undelegate
              </Button>
              <Button
                intent="secondary"
                onClick={() => {
                  onClose();
                  openSelectValidatorModal();
                }}
              >
                Redelegate
              </Button>
              <Button
                intent="tertiary"
                onClick={() => {
                  onClose();
                  openDelegateModal();
                }}
              >
                Delegate
              </Button>
            </Box>
          }
        />
      </Box>
    </BasicModal>
  );
};
