// examples/telescope-authz/components/authz/GrantCard.tsx
import Image from 'next/image';
import { useState } from 'react';
import {
  Box,
  Button,
  IconButton,
  Stack,
  Text,
  TextField,
} from '@interchain-ui/react';

import { getCoin } from '@/configs';
import {
  getChainLogoByChainName,
  PrettyGrant,
  PrettyPermission,
} from '@/utils';
import { useAuthzTx, useGrants } from '@/hooks';

import styles from '@/styles/custom.module.css';

type GrantCardProps = {
  role: 'granter' | 'grantee';
  grant: PrettyGrant;
  chainName: string;
  onViewDetails: () => void;
};

export const GrantCard = ({
  role,
  grant,
  chainName,
  onViewDetails,
}: GrantCardProps) => {
  const [isCopied, setIsCopied] = useState(false);
  const [isRevoking, setIsRevoking] = useState(false);
  const [revokingPermission, setRevokingPermission] =
    useState<PrettyPermission>();

  const { refetch } = useGrants(chainName);
  const { authzTx, createRevokeMsg } = useAuthzTx(chainName);

  const { address, permissions } = grant;

  const isGranter = role === 'granter';
  const token = getCoin(chainName);

  const copy = (text: string) => {
    if (isCopied) return;

    navigator.clipboard
      .writeText(text)
      .then(() => {
        setIsCopied(true);
        setTimeout(() => setIsCopied(false), 800);
      })
      .catch((error) => {
        console.error('Failed to copy:', error);
      });
  };

  const handleRevoke = (permission: PrettyPermission) => {
    setIsRevoking(true);

    authzTx({
      msgs: [createRevokeMsg(permission)],
      onSuccess: () => {
        refetch();
      },
      onComplete: () => {
        setIsRevoking(false);
      },
    });
  };

  return (
    <Box
      px="$10"
      py="$11"
      backgroundColor="$cardBg"
      borderRadius="$lg"
      width="496px"
    >
      <Stack space="$4" attributes={{ alignItems: 'center', mb: '$10' }}>
        <Image
          alt={token.name}
          src={getChainLogoByChainName(chainName)}
          width="30"
          height="30"
          sizes="100vw"
        />
        <Text fontWeight="$semibold" fontSize="$lg">
          {token.name}
        </Text>
      </Stack>

      <Box position="relative" mb="$10">
        <TextField
          id="address"
          label={isGranter ? 'Grantee' : 'Granter'}
          value={address}
          inputClassName={styles.customInput}
        />
        <Box position="absolute" bottom="$2" right="$2">
          <IconButton
            icon={isCopied ? 'checkLine' : 'copy'}
            size="sm"
            intent="secondary"
            iconSize={isCopied ? '$xl' : '$md'}
            onClick={() => copy(address)}
          />
        </Box>
      </Box>

      <Text
        color="$textSecondary"
        fontSize="$sm"
        fontWeight="$semibold"
        lineHeight="$normal"
        attributes={{ mb: '$6' }}
      >
        Permissions
      </Text>

      <Box
        display="flex"
        gap="$6"
        flexWrap="wrap"
        mb="$12"
        height="$12"
        overflow="hidden"
      >
        {permissions.map((permission) => (
          <Button
            key={permission.name}
            size="sm"
            intent="secondary"
            rightIcon={isGranter ? 'close' : 'arrowRightRounded'}
            iconSize={isGranter ? '$lg' : '$2xs'}
            onClick={() => {
              handleRevoke(permission);
              setRevokingPermission(permission);
            }}
            disabled={
              isRevoking && revokingPermission?.name === permission.name
            }
          >
            {permission.name}
          </Button>
        ))}
      </Box>

      <Button intent="tertiary" onClick={onViewDetails} fluidWidth>
        View Details
      </Button>
    </Box>
  );
};

// examples/asset-list-vue/src/components/authz/grant-card.vue
<script setup lang="ts">
import { Box, Stack, Text, IconButton, Button } from '@interchain-ui/vue';
import { defineProps, ref, computed } from 'vue'
import { useChain } from '@interchain-kit/vue';
import { PrettyGrant } from '../../utils/authz/authz';

type GrantCardProps = {
  role: 'granter' | 'grantee';
  grant: PrettyGrant;
  chainName: string;
};

const props = defineProps<GrantCardProps>()
const chainName = ref(props.chainName)
const { address, chain, logoUrl } = useChain(chainName)
const isCopied = ref(false)

const isGranter = computed(() => {
  return props.role === 'granter'
})

const onViewDetails = () => {

}

</script>

<template>
<Box
  px="$10"
  py="$11"
  backgroundColor="$cardBg"
  borderRadius="$lg"
  width="$full"
>
  <Stack space="$4" :attributes="{ alignItems: 'center', mb: '$10' }">
    <img :src="logoUrl" alt="" width="50">
    <Text fontWeight="$semibold" fontSize="$lg">
      {{chain.prettyName}}
    </Text>
  </Stack>
  <Box position="relative" mb="$10">
    {{ isGranter ? 'Grantee' : 'Granter' }}
    <input type="text" :value="grant.address "/>
    <Box position="absolute" bottom="$2" right="$2">
      <IconButton
        :icon="isCopied ? 'checkLine' : 'copy'"
        size="sm"
        intent="secondary"
        :iconSize="isCopied ? '$xl' : '$md'"
      />
    </Box>
    <Text
      color="$textSecondary"
      fontSize="$sm"
      fontWeight="$semibold"
      lineHeight="$normal"
      :attributes="{ mb: '$6' }"
    >
      Permissions
    </Text>
    <Box
      display="flex"
      gap="$6"
      flexWrap="wrap"
      mb="$12"
      height="$12"
      overflow="hidden"
    >
      <Button
        v-for="permission in grant.permissions"
        :key="permission.name"
        size="sm"
        intent="secondary"
        rightIcon="close"
        iconSize="$lg"
        @click=""
      >
        {{permission.name}}
      </Button>
    </Box>
    <Button intent="tertiary" @click="onViewDetails">
      View Details
    </Button>
  </Box>
</Box>
</template>

<style scoped></style>
