// examples/asset-list-vue/src/components/asset-list/assets-overview.vue
<script setup lang="ts">
import { ref, computed, defineProps } from 'vue'
import SingleChain from './single-chain.vue';
import { useTotalAssets } from '../../composables/useTotalAssets';
import { PrettyAsset } from './asset-list-section.vue'
import { truncDecimals, formatDollarValue, AvailableItem, prettyAssetToTransferItem } from '../../utils/format';
import { useAssets } from '../../composables/useAssets';
import DropdownTransferModal from './dropdown-transfer-modal.vue'
import RowTransferModal from './row-transfer-modal.vue';
import BigNumber from 'bignumber.js';
import { useDisclosure } from '../../composables/useDisclosure';
import { CoinDenom, PriceHash, Transfer } from '../../utils/types';

export type TransferValues = typeof Transfer[keyof typeof Transfer];

export type TransferInfo = {
  type: TransferValues;
  sourceChainName: string;
  destChainName: string;
  token: AvailableItem;
};
const props = defineProps<{
  isLoading: Boolean,
  assets: Array<PrettyAsset>,
  prices: PriceHash,
  selectedChainName: string,
}>()

const chainName = ref(props.selectedChainName)
const data = useTotalAssets(chainName)
const { nativeAssets, ibcAssets: ibcAsts } = useAssets(chainName)
const dropdownTransferInfo = ref<TransferInfo>()
const rowTransferInfo = ref<TransferInfo>()
// modalControls
const modalControl = useDisclosure();
const rowModalControl = useDisclosure();
console.log('data>>', data)

const isNativeAsset = ({ denom }: PrettyAsset) => {
  return !!nativeAssets.find((asset) => asset.base === denom);
};

const getChainName = (ibcDenom: CoinDenom) => {
  const nativeAsset = nativeAssets.find((asset) => asset.base === ibcDenom)
  if (nativeAsset) {
    return chainName.value
  }
  const asset = ibcAsts.find((asset) => asset.base === ibcDenom);
  const ibcChainName = asset?.traces?.[0].counterparty.chain_name;
  if (!ibcChainName) throw Error('chainName not found for ibcDenom: ' + ibcDenom);
  return ibcChainName;
};

const assetsToShow = computed(() => {
  const returnAssets = props.assets?.map((asset) => {
    return {
      imgSrc: asset.logoUrl ?? '',
      symbol: asset.symbol,
      denom: asset.denom,
      name: asset.prettyChainName,
      tokenAmount: truncDecimals(asset.displayAmount, 6),
      tokenAmountPrice: formatDollarValue(asset.dollarValue, asset.amount),
      chainName: asset.prettyChainName,
      showDeposit: !isNativeAsset(asset),
      showWithdraw: !isNativeAsset(asset),
      onDeposit: () => {
        console.log('onDeposit..', asset)
        const sourceChainName = getChainName(asset.denom);
        const denom = asset.denom
        rowTransferInfo.value = {
          sourceChainName,
          type: Transfer.Deposit,
          destChainName: props.selectedChainName,
          token: {
            ...prettyAssetToTransferItem(asset),
            priceDisplayAmount: 0,
            available: 0,
            denom
          }
        }
        rowModalControl.open();
      },
      onWithdraw: () => {
        console.log('onWithdraw..', asset)
        const destChainName = getChainName(asset.denom);

        rowTransferInfo.value = {
          sourceChainName: props.selectedChainName,
          type: Transfer.Withdraw,
          destChainName,
          token: prettyAssetToTransferItem(asset)
        }

        rowModalControl.open();
      }
    }
  })
  return returnAssets
})

const ibcAssets = computed(() => {
  return props.assets?.filter((asset) => !isNativeAsset(asset)) || []
})

const onWithdrawAsset = () => {
  const destChainName = getChainName(ibcAssets.value[0].denom)
  dropdownTransferInfo.value = {
    sourceChainName: props.selectedChainName,
    type: Transfer.Withdraw,
    destChainName,
    token: prettyAssetToTransferItem(ibcAssets.value[0])
  }
}

const onDepositAsset = () => {
  const sourceChainName = getChainName(ibcAssets.value[0].denom);
  const sourceChainAssetDenom = ibcAssets.value[0].denom;
  dropdownTransferInfo.value = {
    sourceChainName,
    type: Transfer.Deposit,
    destChainName: props.selectedChainName,
    token: {
      ...prettyAssetToTransferItem(ibcAssets.value[0]),
      available: 0,
      priceDisplayAmount: 0,
      denom: sourceChainAssetDenom
    }
  }
  // modalControl.open();
};

const setTransferInfo = (info: TransferInfo) => {
  dropdownTransferInfo.value = info
}

const hasBalance = computed(() => {
  return ibcAssets.value.some((asset) => new BigNumber(asset.amount).gt(0))
})
</script>

<template>
  <SingleChain
    :isLoading="false"
    title="Your assets"
    :listTitle="`On osmosis`"
    :showDeposit="ibcAssets.length > 0"
    :showWithdraw="hasBalance"
    @onDeposit="onDepositAsset"
    @onWithdraw="onWithdrawAsset"
    :singleChainHeader="{
      label: `Total on ${chainName}`,
      value: data.total,
    }"
    :list="assetsToShow"
  />
  <DropdownTransferModal
    v-if="prices && dropdownTransferInfo"
    :prices="prices"
    :assets="ibcAssets"
    :transferInfoState="{
      transferInfo: dropdownTransferInfo,
      setTransferInfo
    }"
    :modalControl="modalControl"
    @updateData=""
    :selectedChainName="selectedChainName"
  />
  <RowTransferModal
    v-if="rowTransferInfo"
    :modalControl="rowModalControl"
    :transferInfo="rowTransferInfo"
  />
</template>

<style scoped></style>

// examples/chain-template/components/asset-list/AssetsOverview.tsx
import React, { useMemo, useState } from 'react';
import { flushSync } from 'react-dom';
import { useChain } from '@cosmos-kit/react';
import BigNumber from 'bignumber.js';
import { ChainName } from 'cosmos-kit';
import { SingleChain, SingleChainProps } from '@interchain-ui/react';

import { useDisclosure, useChainUtils, useTotalAssets } from '@/hooks';
import {
  truncDecimals,
  formatDollarValue,
  prettyAssetToTransferItem,
} from '@/utils';

import { DropdownTransferModal } from './DropdownTransferModal';
import { RowTransferModal } from './RowTransferModal';

import { PrettyAsset, Transfer, TransferInfo } from './types';

interface AssetsOverviewProps {
  isLoading?: boolean;
  assets: PrettyAsset[];
  prices: Record<string, number>;
  selectedChainName: ChainName;
  refetch?: () => void;
}

const AssetsOverview = ({
  assets,
  selectedChainName,
  isLoading,
}: AssetsOverviewProps) => {
  const [dropdownTransferInfo, setTransferInfo] = useState<TransferInfo>();
  const [rowTransferInfo, setRowTransferInfo] = useState<TransferInfo>();

  const { chain } = useChain(selectedChainName);

  const {
    data,
    isLoading: isLoadingTotalAssets,
    refetch,
  } = useTotalAssets(selectedChainName);
  const { getChainName, getNativeDenom, isNativeAsset } =
    useChainUtils(selectedChainName);

  const modalControl = useDisclosure();
  const rowModalControl = useDisclosure();

  const ibcAssets = useMemo(
    () => assets.filter((asset) => !isNativeAsset(asset)),
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [assets]
  );

  const hasBalance = useMemo(
    () => ibcAssets.some((asset) => new BigNumber(asset.amount).gt(0)),
    [ibcAssets]
  );

  const assetsToShow = useMemo(() => {
    const returnAssets: SingleChainProps['list'] = assets.map((asset) => ({
      imgSrc: asset.logoUrl ?? '',
      symbol: asset.symbol,
      denom: asset.denom,
      name: asset.prettyChainName,
      tokenAmount: truncDecimals(asset.displayAmount, 6),
      tokenAmountPrice: formatDollarValue(asset.dollarValue, asset.amount),
      chainName: asset.prettyChainName,
      showDeposit: !isNativeAsset(asset),
      showWithdraw: !isNativeAsset(asset),
      onDeposit: () => {
        const sourceChainName = getChainName(asset.denom);
        const sourceChainNativeDenom = getNativeDenom(sourceChainName);
        flushSync(() => {
          setRowTransferInfo({
            sourceChainName,
            type: Transfer.Deposit,
            destChainName: selectedChainName,
            token: {
              ...prettyAssetToTransferItem(asset),
              priceDisplayAmount: 0,
              available: 0,
              denom: sourceChainNativeDenom,
            },
          });
        });

        rowModalControl.onOpen();
      },
      onWithdraw: () => {
        const destChainName = getChainName(asset.denom);

        flushSync(() => {
          setRowTransferInfo({
            sourceChainName: selectedChainName,
            type: Transfer.Withdraw,
            destChainName,
            token: prettyAssetToTransferItem(asset),
          });
        });

        rowModalControl.onOpen();
      },
    }));

    return returnAssets;
  }, [
    assets,
    getChainName,
    getNativeDenom,
    isNativeAsset,
    rowModalControl,
    selectedChainName,
  ]);

  const onWithdrawAsset = () => {
    const destChainName = getChainName(ibcAssets[0].denom);
    setTransferInfo({
      sourceChainName: selectedChainName,
      type: Transfer.Withdraw,
      destChainName,
      token: prettyAssetToTransferItem(ibcAssets[0]),
    });
    modalControl.onOpen();
  };

  const onDepositAsset = () => {
    const sourceChainName = getChainName(ibcAssets[0].denom);
    const sourceChainAssetDenom = getNativeDenom(sourceChainName);
    setTransferInfo({
      sourceChainName,
      type: Transfer.Deposit,
      destChainName: selectedChainName,
      token: {
        ...prettyAssetToTransferItem(ibcAssets[0]),
        available: 0,
        priceDisplayAmount: 0,
        denom: sourceChainAssetDenom,
      },
    });
    modalControl.onOpen();
  };

  return (
    <>
      <SingleChain
        isLoading={isLoading || isLoadingTotalAssets}
        title="Your Assets"
        listTitle={`On ${chain.pretty_name}`}
        showDeposit={ibcAssets.length > 0}
        showWithdraw={hasBalance}
        onDeposit={onDepositAsset}
        onWithdraw={onWithdrawAsset}
        singleChainHeader={{
          label: `Total on ${chain.pretty_name}`,
          value: `${data?.total ?? 0}`,
        }}
        list={assetsToShow}
      />

      {data && dropdownTransferInfo && (
        <DropdownTransferModal
          prices={data?.prices ?? {}}
          assets={ibcAssets}
          transferInfoState={{
            transferInfo: dropdownTransferInfo,
            setTransferInfo,
          }}
          modalControl={modalControl}
          updateData={refetch}
          selectedChainName={selectedChainName}
        />
      )}

      {rowTransferInfo && (
        <RowTransferModal
          prices={data?.prices ?? {}}
          transferInfo={rowTransferInfo}
          updateData={refetch}
          modalControl={rowModalControl}
          selectedChainName={selectedChainName}
        />
      )}
    </>
  );
};

export default AssetsOverview;
