// examples/vue-example/src/components/stake-tokens/my-validators-modals/redelegate-modal.vue
<script setup lang="ts">
import { Box, Modal, Button } from '@interchain-ui/vue'
import { ref, defineProps, computed } from 'vue'
import { ExtendedValidator } from '../../../utils/stake-tokens/staking';
import { useAssets } from '../../../composables/common/useAssets';
import { calcDollarValue, shiftDigits } from '../../../utils/stake-tokens/math';
import { usePrices } from '../../../composables/common/usePrices';
import { cosmos, StdFee } from '../../../codegen';
import { useChain } from '@interchain-kit/vue';
import { coins } from '@cosmjs/stargate';
import { useStargateClient } from '../../../composables/common/useStargateClient';

const { beginRedelegate } = cosmos.staking.v1beta1.MessageComposer.fromPartial;

const props = defineProps<{
  isOpen: boolean;
  selectedValidator: ExtendedValidator;
  validatorToRedelegate: ExtendedValidator;
  chainName: string;
}>()

const chainName = ref(props.chainName)
const { address } = useChain(chainName)
const { allAssets } = useAssets(chainName)
const { prices } = usePrices(chainName)
const stargazeClient = useStargateClient(chainName)
const isSigning = ref(false)
const amount = ref(0)
const emit = defineEmits<{
  (event: 'close'): void;
  (event: 'success'): void;
}>();

const closeModal = () => {
  emit('close')
}

const notionalValue = computed(() => {
  if (prices.value && amount.value) {
    return calcDollarValue(allAssets[0].base, amount.value, prices.value)
  }
  return ''
})

const exponent = computed(() => {
  return (allAssets[0].denom_units.find((unit) => unit.denom === allAssets[0].display))?.exponent
})

const handleRedelegate = async() => {
  if (!address.value || !amount.value || !exponent.value) return;
  const msg = beginRedelegate({
    delegatorAddress: address.value,
    validatorSrcAddress: props.selectedValidator.address,
    validatorDstAddress: props.validatorToRedelegate.address,
    amount: {
      denom: allAssets[0].base,
      amount: shiftDigits(amount.value, exponent.value),
    },
  });
  console.log('msg>>', msg)
  
  const gasEstimate = await stargazeClient.value.simulate(
    address.value,
    [msg],
  );
  const gasLimit = Math.ceil(gasEstimate * 1.2);
  console.log('gasLimit>', gasLimit)

  const fee: StdFee = {
    amount: coins('1000', allAssets[0].base),
    gas: String(gasLimit)
  }

  isSigning.value = true
  try {
    const res = await stargazeClient.value.signAndBroadcast(
      address.value,
      [msg],
      fee
    )
    console.log('[signAndBroadcast result]', res)
    emit('success')
    closeModal()
  } catch(e) {
    console.error(e)
  } finally {
    isSigning.value = false
  }
}

</script>
<template>
<Modal
  header="header"
  :isOpen="isOpen"
  @close="closeModal"
>
  <Box :width="{ mobile: '100%', tablet: '$containerSm' }" mt="$6">
    <b>From: {{ selectedValidator.name }}</b>
    <div>
      Your delegation
      <div>tokenAmount: {{selectedValidator.delegation}}</div>
      <div>tokenName: {{ allAssets[0].symbol }}</div>
    </div>
    <b>To: {{ validatorToRedelegate.name }}</b>
  </Box>
  <div>
    <img :src="allAssets[0].logo_URIs?.png || allAssets[0].logo_URIs?.svg" width="40">
    <input type="text" v-model="amount" />
    <div>notionalValue: ${{ notionalValue }}</div>
  </div>
  <Box mt="$12">
    <Button
      intent="tertiary"
      fluidWidth
      @click="handleRedelegate"
    >
      Redelegate
    </Button>
  </Box>
</Modal>
</template>
<style scoped></style>

// examples/stake-tokens/components/staking/RedelegateModal.tsx
import { useState } from 'react';
import { cosmos } from 'interchain-query';
import { useChain } from '@cosmos-kit/react';
import { ChainName } from 'cosmos-kit';
import {
  BasicModal,
  Box,
  Button,
  StakingDelegateCard,
  StakingDelegateInput,
  Text,
} from '@interchain-ui/react';
import BigNumber from 'bignumber.js';

import {
  calcDollarValue,
  getAssetLogoUrl,
  isGreaterThanZero,
  shiftDigits,
  type ExtendedValidator as Validator,
} from '@/utils';
import { getCoin, getExponent } from '@/config';
import { Prices, UseDisclosureReturn, useTx } from '@/hooks';

const { beginRedelegate } = cosmos.staking.v1beta1.MessageComposer.fromPartial;

export const RedelegateModal = ({
  updateData,
  chainName,
  modalControl,
  selectedValidator,
  validatorToRedelegate,
  prices,
}: {
  updateData: () => void;
  chainName: ChainName;
  selectedValidator: Validator;
  validatorToRedelegate: Validator;
  modalControl: UseDisclosureReturn;
  prices: Prices;
}) => {
  const { address } = useChain(chainName);

  const [amount, setAmount] = useState<number | undefined>(0);
  const [isRedelegating, setIsRedelegating] = useState(false);
  const [, forceUpdate] = useState(0);

  const coin = getCoin(chainName);
  const exp = getExponent(chainName);

  const { tx } = useTx(chainName);

  const closeRedelegateModal = () => {
    setAmount(0);
    setIsRedelegating(false);
    modalControl.onClose();
  };

  const onRedelegateClick = async () => {
    if (!address || !amount) return;

    setIsRedelegating(true);

    const msg = beginRedelegate({
      delegatorAddress: address,
      validatorSrcAddress: selectedValidator.address,
      validatorDstAddress: validatorToRedelegate.address,
      amount: {
        denom: coin.base,
        amount: shiftDigits(amount, exp),
      },
    });

    await tx([msg], {
      onSuccess: () => {
        updateData();
        closeRedelegateModal();
      },
    });

    setIsRedelegating(false);
  };

  const maxAmount = selectedValidator.delegation;

  return (
    <BasicModal
      title="Redelegate"
      isOpen={modalControl.isOpen}
      onClose={closeRedelegateModal}
    >
      <Box width={{ mobile: '100%', tablet: '$containerSm' }} mt="$6">
        <RedelegateLabel
          type="from"
          validatorName={selectedValidator?.name}
          mb="20px"
        />

        <StakingDelegateCard
          label="Your Delegation"
          tokenAmount={selectedValidator?.delegation}
          tokenName={coin.symbol}
          attributes={{ mb: '$12' }}
        />

        <RedelegateLabel
          type="to"
          validatorName={validatorToRedelegate.name}
          mb="20px"
        />

        <StakingDelegateInput
          inputToken={{
            tokenName: coin.symbol,
            tokenIconUrl: getAssetLogoUrl(coin),
          }}
          value={amount}
          notionalValue={
            amount ? calcDollarValue(coin.base, amount, prices) : undefined
          }
          onValueInput={(val) => {
            if (!val) {
              setAmount(undefined);
              return;
            }

            if (new BigNumber(val).gt(maxAmount)) {
              setAmount(Number(maxAmount));
              forceUpdate((n) => n + 1);
              return;
            }

            setAmount(Number(val));
          }}
          partials={[
            {
              label: '1/2',
              onClick: () => {
                setAmount(new BigNumber(maxAmount).dividedBy(2).toNumber());
              },
            },
            {
              label: '1/3',
              onClick: () => {
                setAmount(new BigNumber(maxAmount).dividedBy(3).toNumber());
              },
            },
            {
              label: 'Max',
              onClick: () => setAmount(Number(maxAmount)),
            },
          ]}
        />
      </Box>

      <Box mt="$12">
        <Button
          intent="tertiary"
          onClick={onRedelegateClick}
          isLoading={isRedelegating}
          disabled={!isGreaterThanZero(amount) || isRedelegating}
          fluidWidth
        >
          Redelegate
        </Button>
      </Box>
    </BasicModal>
  );
};

const RedelegateLabel = ({
  type,
  validatorName,
  mb,
}: {
  type: 'from' | 'to';
  validatorName: string;
  mb?: string;
}) => {
  return (
    <Text fontSize="$md" attributes={{ mb }}>
      {type === 'from' ? 'From' : 'To'}&nbsp;
      <Text as="span" fontSize="$md" fontWeight="$semibold">
        {validatorName}
      </Text>
    </Text>
  );
};
