// examples/asset-list-vue/src/views/single-chain.vue
<script setup lang="ts">
import Layout from '@/components/common/Layout.vue'
import WalletSection from '@/components/wallet/Wallet.vue'
import AssetListSection from '@/components/asset-list/AssetListSection.vue';

</script>

<template>
  <Layout>
    <WalletSection :isMultiChain="false" />
    <AssetListSection  />
  </Layout>
</template>

<style scoped></style>

// examples/ibc-transfer/pages/single-chain.tsx
import { ReactNoSSR } from '@interchain-ui/react-no-ssr';
import { defaultChainName } from '@/config';
import { AssetListSection, Layout, WalletSection } from '@/components';

export default function SingleChain() {
  return (
    <Layout>
      <WalletSection isMultiChain={false} />
      <ReactNoSSR>
        <AssetListSection chainName={defaultChainName} />
      </ReactNoSSR>
    </Layout>
  );
}
