// examples/injective/components/common/Header.tsx
import { Link, Box, Button, Icon, Text, useTheme, useColorModeValue } from '@interchain-ui/react';
import { dependencies } from '@/config';

const stacks = ['Cosmos Kit', 'Next.js'];

const osmojs = dependencies[0];

export function Header() {
  const { theme, setTheme } = useTheme();

  const toggleColorMode = () => {
    setTheme(theme === 'light' ? 'dark' : 'light');
  };

  return (
    <>
      <Box display="flex" justifyContent="end" mb="$8">
        <Button
          intent="secondary"
          size="sm"
          attributes={{
            paddingX: 0,
          }}
          onClick={toggleColorMode}
        >
          <Icon name={useColorModeValue('moonLine', 'sunLine')} />
        </Button>
      </Box>

      <Box textAlign="center">
        <Text
          as="h1"
          fontWeight="$extrabold"
          fontSize={{ mobile: '$6xl', tablet: '$10xl' }}
          attributes={{
            marginBottom: '$8',
          }}
        >
          Create Cosmos App
        </Text>
        <Text as="h2" fontWeight="$bold">
          <Text
            as="span"
            fontSize={{ mobile: '$3xl', tablet: '$8xl', desktop: '$8xl' }}
          >
            Welcome to&nbsp;
          </Text>
          <Text
            as="span"
            fontSize={{ mobile: '$3xl', tablet: '$8xl', desktop: '$8xl' }}
            color={useColorModeValue('$primary500', '$primary200')}
          >
            {stacks.join(' + ')}
            {' + '}

            <Link
              href={osmojs.name}
              target="_blank"
              rel="noreferrer"
              attributes={{
                color: useColorModeValue('$primary500', '$primary200'),
                fontSize: { mobile: '$4xl', tablet: '$8xl', desktop: '$8xl' },
              }}
            >
              {osmojs.name}
            </Link>
          </Text>
        </Text>
      </Box>
    </>
  );
}

// examples/asset-list-vue/src/components/common/Header.vue
<script setup lang="ts">
import { Link, Text, Box, Container, Button, Icon } from '@interchain-ui/vue';
import { dependencies } from '@/config/features'
const stacks = ['Interchain Kit', 'Vue'];
const osmojs = dependencies[0];

</script>

<template>
  <Box display="flex" justifyContent="end" mb="$8">
    <Button intent="secondary" size="sm" :attributes="{ paddingX: 0, }">
      <Icon name="moonLine" />
    </Button>
  </Box>

  <Box textAlign="center">
    <Text as="h1" fontWeight="$extrabold" :fontSize="{ mobile: '$3xl', tablet: '$4xl', desktop: '$10xl' }" :attributes="{
      marginBottom: '$6',
    }">
      Create Cosmos App
    </Text>
    <Text as="h1" fontWeight="$bold">
      <Text as="span" :fontSize="{ mobile: '$4xl', tablet: '$8xl', desktop: '$8xl' }">
        Welcome to&nbsp;
      </Text>
      <Text as="span" :fontSize="{ mobile: '$4xl', tablet: '$8xl', desktop: '$8xl' }" color="$primary500">
        {{ stacks.join(' + ') }} {{ ' + ' }}
        <Link href={osmojs.name} target="_blank" rel="noreferrer" :attributes="{
          fontSize: { mobile: '$4xl', tablet: '$8xl', desktop: '$8xl' },
        }">
        {{ osmojs.name }}
        </Link>
      </Text>
    </Text>
  </Box>
</template>

<style scoped></style>
