// examples/asset-list-vue/src/components/asset-list/asset-list-section.vue
<script setup lang="ts">
import { useChain } from '@interchain-kit/vue'
import { WalletState } from '@interchain-kit/core'
import { ref } from 'vue'
import AssetsOverview from './assets-overview.vue';
import { Box, Text } from '@interchain-ui/vue';

export type PrettyAsset = {
  logoUrl: string | undefined;
  symbol: string;
  prettyChainName: string;
  displayAmount: string;
  dollarValue: string;
  amount: string;
  denom: string;
};

const chainName = ref('osmosis')
const { status } = useChain(chainName)

</script>

<template>
  <Box
    v-if="status === WalletState.Disconnected || !status"
    maxWidth="768px" marginX="auto" marginBottom="60px"
  >
    <Text
      fontSize="$xl"
      fontWeight="$semibold"
      :attributes="{ marginBottom: '$10' }"
    >
      My assets
    </Text>
    <Box
      height="160px"
      bg="$cardBg"
      borderRadius="$md"
      p="$6"
      display="flex"
      justifyContent="center"
      alignItems="center"
    >
      <Text fontSize="$md" color="$textSecondary">
        Connect the wallet to see the assets
      </Text>
    </Box>
  </Box>
  <Box v-else maxWidth="$containerMd" marginX="auto" marginBottom="$17">
    <AssetsOverview
      :selectedChainName="chainName"
    />
  </Box>
</template>

<style scoped></style>

// examples/asset-list/components/asset-list/AssetListSection.tsx
import React from 'react';
import { Text, Box } from '@interchain-ui/react';
import AssetsOverview from './AssetsOverview';
import { useChain } from '@cosmos-kit/react';
import { useAssets } from '../../hooks';
import { ChainName } from 'cosmos-kit';

interface IProps {
  chainName: ChainName;
}

export const AssetListSection: React.FC<IProps> = ({ chainName }) => {
  const { isWalletConnected } = useChain(chainName);
  const { data, isLoading, refetch } = useAssets(chainName);

  if (!isWalletConnected) {
    return (
      <Box maxWidth="768px" marginX="auto" marginBottom="60px">
        <Text
          fontSize="$xl"
          fontWeight="$semibold"
          attributes={{ marginBottom: '$10' }}
        >
          My assets
        </Text>

        <Box
          height="160px"
          bg="$cardBg"
          borderRadius="$md"
          p="$6"
          display="flex"
          justifyContent="center"
          alignItems="center"
        >
          <Text fontSize="$md" color="$textSecondary">
            Connect the wallet to see the assets
          </Text>
        </Box>
      </Box>
    );
  }

  return (
    <Box maxWidth="$containerMd" marginX="auto" marginBottom="$17">
      <AssetsOverview
        isLoading={isLoading || !data}
        assets={data?.assets ?? []}
        prices={data?.prices ?? {}}
        selectedChainName={chainName}
        refetch={refetch}
      />
    </Box>
  );
};
